//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WopiService_Proxy.Wopi_WebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Wopi_WebService.Wopi_ServiceSoap")]
    public interface Wopi_ServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_Link", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Get_Link(string fileNmae);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/Get_Link", ReplyAction="*")]
        System.IAsyncResult BeginGet_Link(string fileNmae, System.AsyncCallback callback, object asyncState);
        
        string EndGet_Link(System.IAsyncResult result);
        
        // CODEGEN: 参数“documentData”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UploadFile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WopiService_Proxy.Wopi_WebService.UploadFileResponse UploadFile(WopiService_Proxy.Wopi_WebService.UploadFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/UploadFile", ReplyAction="*")]
        System.IAsyncResult BeginUploadFile(WopiService_Proxy.Wopi_WebService.UploadFileRequest request, System.AsyncCallback callback, object asyncState);
        
        WopiService_Proxy.Wopi_WebService.UploadFileResponse EndUploadFile(System.IAsyncResult result);
        
        // CODEGEN: 参数“documentData”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UploadFile_GetLink", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WopiService_Proxy.Wopi_WebService.UploadFile_GetLinkResponse UploadFile_GetLink(WopiService_Proxy.Wopi_WebService.UploadFile_GetLinkRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/UploadFile_GetLink", ReplyAction="*")]
        System.IAsyncResult BeginUploadFile_GetLink(WopiService_Proxy.Wopi_WebService.UploadFile_GetLinkRequest request, System.AsyncCallback callback, object asyncState);
        
        WopiService_Proxy.Wopi_WebService.UploadFile_GetLinkResponse EndUploadFile_GetLink(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete_File", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool Delete_File(string fileNmae);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/Delete_File", ReplyAction="*")]
        System.IAsyncResult BeginDelete_File(string fileNmae, System.AsyncCallback callback, object asyncState);
        
        bool EndDelete_File(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UploadFile", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UploadFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string fileNmae;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] documentData;
        
        public UploadFileRequest() {
        }
        
        public UploadFileRequest(string fileNmae, byte[] documentData) {
            this.fileNmae = fileNmae;
            this.documentData = documentData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UploadFileResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UploadFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool UploadFileResult;
        
        public UploadFileResponse() {
        }
        
        public UploadFileResponse(bool UploadFileResult) {
            this.UploadFileResult = UploadFileResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UploadFile_GetLink", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UploadFile_GetLinkRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string fileNmae;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] documentData;
        
        public UploadFile_GetLinkRequest() {
        }
        
        public UploadFile_GetLinkRequest(string fileNmae, byte[] documentData) {
            this.fileNmae = fileNmae;
            this.documentData = documentData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UploadFile_GetLinkResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UploadFile_GetLinkResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string UploadFile_GetLinkResult;
        
        public UploadFile_GetLinkResponse() {
        }
        
        public UploadFile_GetLinkResponse(string UploadFile_GetLinkResult) {
            this.UploadFile_GetLinkResult = UploadFile_GetLinkResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Wopi_ServiceSoapChannel : WopiService_Proxy.Wopi_WebService.Wopi_ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Get_LinkCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public Get_LinkCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UploadFileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public UploadFileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UploadFile_GetLinkCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public UploadFile_GetLinkCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Delete_FileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public Delete_FileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Wopi_ServiceSoapClient : System.ServiceModel.ClientBase<WopiService_Proxy.Wopi_WebService.Wopi_ServiceSoap>, WopiService_Proxy.Wopi_WebService.Wopi_ServiceSoap {
        
        private BeginOperationDelegate onBeginGet_LinkDelegate;
        
        private EndOperationDelegate onEndGet_LinkDelegate;
        
        private System.Threading.SendOrPostCallback onGet_LinkCompletedDelegate;
        
        private BeginOperationDelegate onBeginUploadFileDelegate;
        
        private EndOperationDelegate onEndUploadFileDelegate;
        
        private System.Threading.SendOrPostCallback onUploadFileCompletedDelegate;
        
        private BeginOperationDelegate onBeginUploadFile_GetLinkDelegate;
        
        private EndOperationDelegate onEndUploadFile_GetLinkDelegate;
        
        private System.Threading.SendOrPostCallback onUploadFile_GetLinkCompletedDelegate;
        
        private BeginOperationDelegate onBeginDelete_FileDelegate;
        
        private EndOperationDelegate onEndDelete_FileDelegate;
        
        private System.Threading.SendOrPostCallback onDelete_FileCompletedDelegate;
        
        public Wopi_ServiceSoapClient() {
        }
        
        public Wopi_ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Wopi_ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Wopi_ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Wopi_ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<Get_LinkCompletedEventArgs> Get_LinkCompleted;
        
        public event System.EventHandler<UploadFileCompletedEventArgs> UploadFileCompleted;
        
        public event System.EventHandler<UploadFile_GetLinkCompletedEventArgs> UploadFile_GetLinkCompleted;
        
        public event System.EventHandler<Delete_FileCompletedEventArgs> Delete_FileCompleted;
        
        public string Get_Link(string fileNmae) {
            return base.Channel.Get_Link(fileNmae);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGet_Link(string fileNmae, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGet_Link(fileNmae, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public string EndGet_Link(System.IAsyncResult result) {
            return base.Channel.EndGet_Link(result);
        }
        
        private System.IAsyncResult OnBeginGet_Link(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string fileNmae = ((string)(inValues[0]));
            return this.BeginGet_Link(fileNmae, callback, asyncState);
        }
        
        private object[] OnEndGet_Link(System.IAsyncResult result) {
            string retVal = this.EndGet_Link(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGet_LinkCompleted(object state) {
            if ((this.Get_LinkCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.Get_LinkCompleted(this, new Get_LinkCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void Get_LinkAsync(string fileNmae) {
            this.Get_LinkAsync(fileNmae, null);
        }
        
        public void Get_LinkAsync(string fileNmae, object userState) {
            if ((this.onBeginGet_LinkDelegate == null)) {
                this.onBeginGet_LinkDelegate = new BeginOperationDelegate(this.OnBeginGet_Link);
            }
            if ((this.onEndGet_LinkDelegate == null)) {
                this.onEndGet_LinkDelegate = new EndOperationDelegate(this.OnEndGet_Link);
            }
            if ((this.onGet_LinkCompletedDelegate == null)) {
                this.onGet_LinkCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGet_LinkCompleted);
            }
            base.InvokeAsync(this.onBeginGet_LinkDelegate, new object[] {
                        fileNmae}, this.onEndGet_LinkDelegate, this.onGet_LinkCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WopiService_Proxy.Wopi_WebService.UploadFileResponse WopiService_Proxy.Wopi_WebService.Wopi_ServiceSoap.UploadFile(WopiService_Proxy.Wopi_WebService.UploadFileRequest request) {
            return base.Channel.UploadFile(request);
        }
        
        public bool UploadFile(string fileNmae, byte[] documentData) {
            WopiService_Proxy.Wopi_WebService.UploadFileRequest inValue = new WopiService_Proxy.Wopi_WebService.UploadFileRequest();
            inValue.fileNmae = fileNmae;
            inValue.documentData = documentData;
            WopiService_Proxy.Wopi_WebService.UploadFileResponse retVal = ((WopiService_Proxy.Wopi_WebService.Wopi_ServiceSoap)(this)).UploadFile(inValue);
            return retVal.UploadFileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult WopiService_Proxy.Wopi_WebService.Wopi_ServiceSoap.BeginUploadFile(WopiService_Proxy.Wopi_WebService.UploadFileRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginUploadFile(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginUploadFile(string fileNmae, byte[] documentData, System.AsyncCallback callback, object asyncState) {
            WopiService_Proxy.Wopi_WebService.UploadFileRequest inValue = new WopiService_Proxy.Wopi_WebService.UploadFileRequest();
            inValue.fileNmae = fileNmae;
            inValue.documentData = documentData;
            return ((WopiService_Proxy.Wopi_WebService.Wopi_ServiceSoap)(this)).BeginUploadFile(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WopiService_Proxy.Wopi_WebService.UploadFileResponse WopiService_Proxy.Wopi_WebService.Wopi_ServiceSoap.EndUploadFile(System.IAsyncResult result) {
            return base.Channel.EndUploadFile(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public bool EndUploadFile(System.IAsyncResult result) {
            WopiService_Proxy.Wopi_WebService.UploadFileResponse retVal = ((WopiService_Proxy.Wopi_WebService.Wopi_ServiceSoap)(this)).EndUploadFile(result);
            return retVal.UploadFileResult;
        }
        
        private System.IAsyncResult OnBeginUploadFile(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string fileNmae = ((string)(inValues[0]));
            byte[] documentData = ((byte[])(inValues[1]));
            return this.BeginUploadFile(fileNmae, documentData, callback, asyncState);
        }
        
        private object[] OnEndUploadFile(System.IAsyncResult result) {
            bool retVal = this.EndUploadFile(result);
            return new object[] {
                    retVal};
        }
        
        private void OnUploadFileCompleted(object state) {
            if ((this.UploadFileCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.UploadFileCompleted(this, new UploadFileCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void UploadFileAsync(string fileNmae, byte[] documentData) {
            this.UploadFileAsync(fileNmae, documentData, null);
        }
        
        public void UploadFileAsync(string fileNmae, byte[] documentData, object userState) {
            if ((this.onBeginUploadFileDelegate == null)) {
                this.onBeginUploadFileDelegate = new BeginOperationDelegate(this.OnBeginUploadFile);
            }
            if ((this.onEndUploadFileDelegate == null)) {
                this.onEndUploadFileDelegate = new EndOperationDelegate(this.OnEndUploadFile);
            }
            if ((this.onUploadFileCompletedDelegate == null)) {
                this.onUploadFileCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnUploadFileCompleted);
            }
            base.InvokeAsync(this.onBeginUploadFileDelegate, new object[] {
                        fileNmae,
                        documentData}, this.onEndUploadFileDelegate, this.onUploadFileCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WopiService_Proxy.Wopi_WebService.UploadFile_GetLinkResponse WopiService_Proxy.Wopi_WebService.Wopi_ServiceSoap.UploadFile_GetLink(WopiService_Proxy.Wopi_WebService.UploadFile_GetLinkRequest request) {
            return base.Channel.UploadFile_GetLink(request);
        }
        
        public string UploadFile_GetLink(string fileNmae, byte[] documentData) {
            WopiService_Proxy.Wopi_WebService.UploadFile_GetLinkRequest inValue = new WopiService_Proxy.Wopi_WebService.UploadFile_GetLinkRequest();
            inValue.fileNmae = fileNmae;
            inValue.documentData = documentData;
            WopiService_Proxy.Wopi_WebService.UploadFile_GetLinkResponse retVal = ((WopiService_Proxy.Wopi_WebService.Wopi_ServiceSoap)(this)).UploadFile_GetLink(inValue);
            return retVal.UploadFile_GetLinkResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult WopiService_Proxy.Wopi_WebService.Wopi_ServiceSoap.BeginUploadFile_GetLink(WopiService_Proxy.Wopi_WebService.UploadFile_GetLinkRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginUploadFile_GetLink(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginUploadFile_GetLink(string fileNmae, byte[] documentData, System.AsyncCallback callback, object asyncState) {
            WopiService_Proxy.Wopi_WebService.UploadFile_GetLinkRequest inValue = new WopiService_Proxy.Wopi_WebService.UploadFile_GetLinkRequest();
            inValue.fileNmae = fileNmae;
            inValue.documentData = documentData;
            return ((WopiService_Proxy.Wopi_WebService.Wopi_ServiceSoap)(this)).BeginUploadFile_GetLink(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WopiService_Proxy.Wopi_WebService.UploadFile_GetLinkResponse WopiService_Proxy.Wopi_WebService.Wopi_ServiceSoap.EndUploadFile_GetLink(System.IAsyncResult result) {
            return base.Channel.EndUploadFile_GetLink(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public string EndUploadFile_GetLink(System.IAsyncResult result) {
            WopiService_Proxy.Wopi_WebService.UploadFile_GetLinkResponse retVal = ((WopiService_Proxy.Wopi_WebService.Wopi_ServiceSoap)(this)).EndUploadFile_GetLink(result);
            return retVal.UploadFile_GetLinkResult;
        }
        
        private System.IAsyncResult OnBeginUploadFile_GetLink(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string fileNmae = ((string)(inValues[0]));
            byte[] documentData = ((byte[])(inValues[1]));
            return this.BeginUploadFile_GetLink(fileNmae, documentData, callback, asyncState);
        }
        
        private object[] OnEndUploadFile_GetLink(System.IAsyncResult result) {
            string retVal = this.EndUploadFile_GetLink(result);
            return new object[] {
                    retVal};
        }
        
        private void OnUploadFile_GetLinkCompleted(object state) {
            if ((this.UploadFile_GetLinkCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.UploadFile_GetLinkCompleted(this, new UploadFile_GetLinkCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void UploadFile_GetLinkAsync(string fileNmae, byte[] documentData) {
            this.UploadFile_GetLinkAsync(fileNmae, documentData, null);
        }
        
        public void UploadFile_GetLinkAsync(string fileNmae, byte[] documentData, object userState) {
            if ((this.onBeginUploadFile_GetLinkDelegate == null)) {
                this.onBeginUploadFile_GetLinkDelegate = new BeginOperationDelegate(this.OnBeginUploadFile_GetLink);
            }
            if ((this.onEndUploadFile_GetLinkDelegate == null)) {
                this.onEndUploadFile_GetLinkDelegate = new EndOperationDelegate(this.OnEndUploadFile_GetLink);
            }
            if ((this.onUploadFile_GetLinkCompletedDelegate == null)) {
                this.onUploadFile_GetLinkCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnUploadFile_GetLinkCompleted);
            }
            base.InvokeAsync(this.onBeginUploadFile_GetLinkDelegate, new object[] {
                        fileNmae,
                        documentData}, this.onEndUploadFile_GetLinkDelegate, this.onUploadFile_GetLinkCompletedDelegate, userState);
        }
        
        public bool Delete_File(string fileNmae) {
            return base.Channel.Delete_File(fileNmae);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginDelete_File(string fileNmae, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginDelete_File(fileNmae, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public bool EndDelete_File(System.IAsyncResult result) {
            return base.Channel.EndDelete_File(result);
        }
        
        private System.IAsyncResult OnBeginDelete_File(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string fileNmae = ((string)(inValues[0]));
            return this.BeginDelete_File(fileNmae, callback, asyncState);
        }
        
        private object[] OnEndDelete_File(System.IAsyncResult result) {
            bool retVal = this.EndDelete_File(result);
            return new object[] {
                    retVal};
        }
        
        private void OnDelete_FileCompleted(object state) {
            if ((this.Delete_FileCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.Delete_FileCompleted(this, new Delete_FileCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void Delete_FileAsync(string fileNmae) {
            this.Delete_FileAsync(fileNmae, null);
        }
        
        public void Delete_FileAsync(string fileNmae, object userState) {
            if ((this.onBeginDelete_FileDelegate == null)) {
                this.onBeginDelete_FileDelegate = new BeginOperationDelegate(this.OnBeginDelete_File);
            }
            if ((this.onEndDelete_FileDelegate == null)) {
                this.onEndDelete_FileDelegate = new EndOperationDelegate(this.OnEndDelete_File);
            }
            if ((this.onDelete_FileCompletedDelegate == null)) {
                this.onDelete_FileCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnDelete_FileCompleted);
            }
            base.InvokeAsync(this.onBeginDelete_FileDelegate, new object[] {
                        fileNmae}, this.onEndDelete_FileDelegate, this.onDelete_FileCompletedDelegate, userState);
        }
    }
}
